# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://receivable.tech
title: receivable.tech
email: joshuamalina@gmail.com
author: Josh Malina
description: > # "Write an awesome description for your new site here. 
  AI solutions for debt collection
copyright: 'Copyright &copy; 2018 receivable.tech. All Rights Reserved.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
#  - title: twitter
#    url: https://twitter.com/SBootstrap
#  - title: github
#    url: https://github.com/IronSummitMedia/startbootstrap
  - title: linkedin
    url: https://www.linkedin.com/in/joshmalina/
